### ISSUE TITLE
Employe non update

### ISSUE THREAD

**Issue by cecilebraun** [PolytechUPMC-ICP/polytechupmc-icp-file-dattente-main-Lgaudelet#1]
@Lgaudelet a écrit
> Dans la fonction update de la classe Employé, j'ai affiché en début et fin de la fonction update les valeurs de l'état de l'employé et de la durée restante de pause ou de travail (0 lorsque l'employé attends).
> 
> Pourtant si ces valeurs sont bien modifiées par la update, d'un appel à l'autre de la fonction, elles sont systématiquement réinitialisées à leur valeur de départ (statut d'attente et durée 0).
> 
> Il me semble pourtant bien modifier les attributs concernés dans update, et ne pas y toucher en dehors de cette fonction.
> 
> Pouvez-vous s'il vous plait m'éclairer sur l'origine sur ce phénomène ? :)

**Comment by cecilebraun** [comment]
Dans l'appel de update, dans la fonction [run](https://github.com/PolytechUPMC-ICP/polytechupmc-icp-file-dattente-main-Lgaudelet/blob/master/Simulateur.cc#L32-L34) vous utilisez la boucle
`for(auto emp: emp_vect)`
Vous accédez ici aux éléments de emp_vect par valeur c'est à dire à une copie du contenu, la modification n'est donc faites que sur la copie.
Vous avez donc besoin de faire la modification sur une référence de l'élément.
`for(auto& emp: emp_vect)`

**Comment by Lgaudelet** [comment]
Merci beaucoup!
